[package]
name = "wrsrvd"
edition.workspace = true
version.workspace = true
license.workspace = true

[features]
# Enable the Winit development backend (requires display server).
# Build with: cargo build -p wrsrvd --features winit
winit = ["smithay/renderer_gl", "smithay/backend_winit"]

[dependencies]
wayray-protocol = { workspace = true, features = ["quic-tls"] }
wayray-wm-protocol = { workspace = true, features = ["server"] }
tracing.workspace = true
tracing-subscriber.workspace = true
miette.workspace = true
thiserror.workspace = true
serde.workspace = true
ctrlc = "3"
quinn.workspace = true
rustls.workspace = true
rcgen.workspace = true
tokio.workspace = true
sea-orm.workspace = true
getrandom = "0.3"

smithay = { version = "0.7", default-features = false, features = [
    "wayland_frontend",
    "desktop",
    "renderer_pixman",
] }
